---
apiVersion: v1
kind: Pod
metadata:
  name: backend-services-container
spec:
  imagePullSecrets:
    - name: artifact-registry-secret
  containers:
    - name: backend-services-container
      image: {{.Values.backend_services.image}}
      ports:
        - containerPort: {{.Values.backend_services.port}}