---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.app.name}}-ingress
spec:
  rules:
    - host: {{.Values.ingress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-app-service    # Point to the backend pod.
                port:
                  number: {{.Values.backend_services.port}}